version: '3.4'
services:
  postgresql:
    image: postgres:9.6
    ports:
      - '5432:5432'
    volumes:
      - postgresql:/var/lib/postgresql/data:delegated
      - ./database-setup.sql:/database-setup.sql:delegated
    environment:
      POSTGRES_USER: notesadmin
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgresql:
